export { default as CategoryRouter } from "./category";
export { default as RolRouter } from "./rol";
export { default as UserRouter } from "./user";
export { default as ProductRouter } from "./product";
export { default as DiscountRouter } from "./discount";
export { default as InventoryRouter } from "./inventory";
export { default as CustomerRouter } from "./customer";
export { default as PaymentRouter } from "./payment";
export { default as AuthRouter } from "./auth";
